{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "hello2.serviceAccountName" . }}
  labels:
{{ include "hello2.labels" . | indent 4 }}
{{- end -}}
